### PR TITLE
fix: line break issue

### LINKED ISSUE #38: Line Breaks are getting removed
The relevance scoring editing messed up my formatting. This is not good. Im editing from mobile now

_Originally posted by @0x4007 in https://github.com/ubiquity/devpool-directory-tasks/issues/46#issuecomment-2418094146_

### PR DESCRIPTION
**Pull request by sshivaditya2019**
Resolves #38 

- Resolves the problem of line breaks being removed.

### CODE REVIEW

File: src/handlers/issue-deduplication.ts [hunk 1]
```diff
@@ -259,5 +259,5 @@ export function removeFootnotes(content: string): string {
       contentWithoutFootnotes = contentWithoutFootnotes.replace(new RegExp(`\\[\\^${footnoteNumber}\\^\\]`, "g"), "");
     });
   }
-  return contentWithoutFootnotes.replace(/\n{2,}/g, "\n").trim();
+  return contentWithoutFootnotes.replace(/\n{2,}/g, "\n");
```
Comment (0x4007) [inline src/handlers/issue-deduplication.ts:262]: Why are you replacing line breaks at all? You should just leave them as is.

**Comment by 0x4007** [comment]
You should post QA but its such a small change so I'll let it slide
